name: caloriematefyp
description: Flutter app with Signup Page, Google Authentication and MongoDB backend.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP API calls (for MongoDB backend)
  http: ^1.2.1

  # Google Sign In
  google_sign_in: ^6.2.1

  # Secure token storage
  flutter_secure_storage: ^9.0.0

  # Local storage
  shared_preferences: ^2.2.2

  # Fonts
  google_fonts: ^6.2.1

  # iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png
    - assets/images/screen1.png
    - assets/images/health_icon.png
    - assets/images/screen2.png
    - assets/images/screen3.png
    - assets/images/screen4.png
    - assets/images/History.png
    - assets/images/compare.png
    - assets/images/scan.png